export const DEFAULT_CATEGORIES = Object.freeze([
  {
    id: "person",
    labelKo: "사람",
    labelEn: "person",
    similarityThreshold: 0.24,
    prompts: [
      "a photo of a person",
      "a group of people",
      "a portrait or selfie",
      "people together in a photo",
      "people playing sports",
      "a human being with a visible face",
      "a photo of soccer players",
      "a full-body photo of a human adult",
    ],
  },
  {
    id: "animal",
    labelKo: "동물",
    labelEn: "animal",
    similarityThreshold: 0.25,
    prompts: [
      "a photo of an animal",
      "a pet cat or dog",
      "a close-up photo of a cat",
      "a close-up photo of a dog",
    ],
  },
  {
    id: "food",
    labelKo: "음식",
    labelEn: "food",
    similarityThreshold: 0.25,
    prompts: ["a photo of food", "a meal on a table", "a dish ready to eat"],
  },
  {
    id: "document",
    labelKo: "문서",
    labelEn: "document",
    similarityThreshold: 0.26,
    prompts: ["a photo of a document", "a page with printed text", "a paper document"],
  },
  {
    id: "receipt",
    labelKo: "영수증",
    labelEn: "receipt",
    similarityThreshold: 0.26,
    prompts: ["a photo of a receipt", "a shopping receipt", "a printed payment receipt"],
  },
  {
    id: "landscape",
    labelKo: "풍경",
    labelEn: "landscape",
    similarityThreshold: 0.245,
    prompts: [
      "a landscape photo",
      "a scenic outdoor view",
      "a beach or ocean landscape",
      "a mountain landscape",
      "a panoramic view from a high place",
    ],
  },
  {
    id: "building",
    labelKo: "건물",
    labelEn: "building",
    similarityThreshold: 0.245,
    prompts: ["a photo of a building", "architecture and buildings", "the exterior of a building"],
  },
  {
    id: "city",
    labelKo: "도시",
    labelEn: "city",
    similarityThreshold: 0.245,
    prompts: ["a city street", "an urban city view", "buildings in a city"],
  },
  {
    id: "indoor",
    labelKo: "실내",
    labelEn: "indoor",
    similarityThreshold: 0.245,
    prompts: ["an indoor photo", "the inside of a room", "an interior space"],
  },
  {
    id: "night",
    labelKo: "야간",
    labelEn: "night",
    similarityThreshold: 0.26,
    prompts: ["a photo taken at night", "a dark night scene", "nighttime lights"],
  },
  {
    id: "screenshot",
    labelKo: "스크린샷",
    labelEn: "screenshot",
    similarityThreshold: 0.28,
    prompts: ["a computer screenshot", "a screenshot of a user interface", "a captured phone screen"],
  },
]);

export const KO_EN = Object.freeze({
  고양이: "cat",
  강아지: "dog",
  개: "dog",
  사람: "person",
  아기: "baby",
  셀카: "selfie",
  동물: "animal",
  음식: "food",
  꽃: "flower",
  나무: "tree",
  자동차: "car",
  차량: "vehicle",
  자전거: "bicycle",
  바다: "ocean",
  산: "mountain",
  하늘: "sky",
  건물: "building",
  도시: "city",
  풍경: "landscape",
  새: "bird",
  물고기: "fish",
  문서: "document",
  영수증: "receipt",
  스크린샷: "screenshot",
  실내: "indoor room",
  야간: "night scene",
  야경: "night city view",
});

export const SEARCH_NEGATIVE_PROMPTS = Object.freeze([
  "a random unrelated photo",
  "background scenery",
  "an unrelated object",
]);
