export const DEFAULT_CATEGORIES = Object.freeze([
  {
    id: "person",
    labelKo: "사람",
    labelEn: "person",
    minimumScore: 0.65,
    prompts: [
      "a photo of a person",
      "a group of people",
      "a portrait or selfie of a person",
      "people together in a photo",
      "people playing sports",
      "a football player",
      "a photo of a baby or child",
    ],
    negativePrompts: [
      "a photo with no people",
      "an empty landscape without a person",
      "an object with no human visible",
    ],
  },
  {
    id: "animal",
    labelKo: "동물",
    labelEn: "animal",
    minimumScore: 0.65,
    prompts: [
      "a photo of an animal",
      "a pet cat or dog",
      "a close-up photo of a cat",
      "a close-up photo of a dog",
    ],
    negativePrompts: [
      "a photo with no animals",
      "an empty room or landscape without an animal",
      "an inanimate object",
    ],
  },
  {
    id: "food",
    labelKo: "음식",
    labelEn: "food",
    minimumScore: 0.65,
    prompts: ["a photo of food", "a meal on a table", "a dish ready to eat"],
    negativePrompts: [
      "a photo with no food",
      "an object that is not edible",
      "a scene without a meal",
    ],
  },
  {
    id: "document",
    labelKo: "문서",
    labelEn: "document",
    minimumScore: 0.7,
    prompts: ["a photo of a document", "a page with printed text", "a paper document"],
    negativePrompts: [
      "a photo without a document",
      "a natural scene with no printed page",
      "an object without readable text",
    ],
  },
  {
    id: "receipt",
    labelKo: "영수증",
    labelEn: "receipt",
    minimumScore: 0.7,
    prompts: ["a photo of a receipt", "a shopping receipt", "a printed payment receipt"],
    negativePrompts: [
      "a photo without a receipt",
      "a document that is not a receipt",
      "a scene with no payment receipt",
    ],
  },
  {
    id: "landscape",
    labelKo: "풍경",
    labelEn: "landscape",
    minimumScore: 0.6,
    prompts: [
      "a landscape photo",
      "a scenic outdoor view",
      "a beach or ocean landscape",
      "a mountain landscape",
    ],
    negativePrompts: [
      "a close-up object with no scenery",
      "an indoor photo without an outdoor view",
      "a document or screenshot",
    ],
  },
  {
    id: "building",
    labelKo: "건물",
    labelEn: "building",
    minimumScore: 0.65,
    prompts: ["a photo of a building", "architecture and buildings", "the exterior of a building"],
    negativePrompts: [
      "a photo with no buildings",
      "a natural landscape without architecture",
      "an indoor close-up object",
    ],
  },
  {
    id: "city",
    labelKo: "도시",
    labelEn: "city",
    minimumScore: 0.65,
    prompts: ["a city street", "an urban city view", "buildings in a city"],
    negativePrompts: [
      "a rural or natural scene",
      "a photo outside a city",
      "an indoor object with no urban view",
    ],
  },
  {
    id: "indoor",
    labelKo: "실내",
    labelEn: "indoor",
    minimumScore: 0.65,
    prompts: ["an indoor photo", "the inside of a room", "an interior space"],
    negativePrompts: [
      "an outdoor photo",
      "an open natural landscape",
      "a street or exterior scene",
    ],
  },
  {
    id: "night",
    labelKo: "야간",
    labelEn: "night",
    minimumScore: 0.7,
    prompts: ["a photo taken at night", "a dark night scene", "nighttime lights"],
    negativePrompts: [
      "a bright colorful daytime photo",
      "a scene clearly illuminated by daylight",
      "a sunny outdoor or bright indoor view",
    ],
  },
  {
    id: "screenshot",
    labelKo: "스크린샷",
    labelEn: "screenshot",
    minimumScore: 0.7,
    prompts: ["a computer screenshot", "a screenshot of a user interface", "a captured phone screen"],
    negativePrompts: [
      "a camera photo of the real world",
      "a natural photograph, not a screenshot",
      "a physical object photographed by a camera",
    ],
  },
]);
export const KO_EN = Object.freeze({
  고양이: "cat",
  강아지: "dog",
  개: "dog",
  사람: "person",
  아기: "baby",
  셀카: "selfie",
  동물: "animal",
  음식: "food",
  꽃: "flower",
  나무: "tree",
  자동차: "car",
  차량: "vehicle",
  자전거: "bicycle",
  바다: "ocean",
  산: "mountain",
  하늘: "sky",
  건물: "building",
  도시: "city",
  풍경: "landscape",
  새: "bird",
  물고기: "fish",
  문서: "document",
  영수증: "receipt",
  스크린샷: "screenshot",
  실내: "indoor room",
  야간: "night scene",
  야경: "night city view",
});

export const SEARCH_NEGATIVE_PROMPTS = Object.freeze([
  "a photo unrelated to the search query",
  "an image that does not contain the requested subject",
  "a completely different subject",
]);
