export const DEFAULT_CATEGORIES = Object.freeze([
  {
    id: "person",
    labelKo: "사람",
    labelEn: "person",
    prompts: ["a photo of a person", "a single person", "a portrait of a person"],
  },
  {
    id: "people",
    labelKo: "여러 사람",
    labelEn: "people",
    prompts: ["a photo of several people", "a group of people", "people together"],
  },
  {
    id: "baby",
    labelKo: "아기",
    labelEn: "baby",
    prompts: ["a photo of a baby", "an infant", "a young baby"],
  },
  {
    id: "selfie",
    labelKo: "셀카",
    labelEn: "selfie",
    prompts: ["a selfie photo", "a person taking a selfie", "a close-up phone selfie"],
  },
  {
    id: "cat",
    labelKo: "고양이",
    labelEn: "cat",
    prompts: ["a photo of a cat", "a pet cat", "a close-up photo of a cat"],
  },
  {
    id: "dog",
    labelKo: "강아지",
    labelEn: "dog",
    prompts: ["a photo of a dog", "a pet dog", "a close-up photo of a dog"],
  },
  {
    id: "food",
    labelKo: "음식",
    labelEn: "food",
    prompts: ["a photo of food", "a meal on a table", "a dish ready to eat"],
  },
  {
    id: "document",
    labelKo: "문서",
    labelEn: "document",
    prompts: ["a photo of a document", "a page with printed text", "a paper document"],
  },
  {
    id: "receipt",
    labelKo: "영수증",
    labelEn: "receipt",
    prompts: ["a photo of a receipt", "a shopping receipt", "a printed payment receipt"],
  },
  {
    id: "landscape",
    labelKo: "풍경",
    labelEn: "landscape",
    prompts: ["a landscape photo", "a scenic outdoor view", "beautiful natural scenery"],
  },
  {
    id: "beach",
    labelKo: "바다",
    labelEn: "beach",
    prompts: ["a photo of the ocean", "a beach by the sea", "waves on the coast"],
  },
  {
    id: "mountain",
    labelKo: "산",
    labelEn: "mountain",
    prompts: ["a photo of a mountain", "a mountain landscape", "hiking in the mountains"],
  },
  {
    id: "building",
    labelKo: "건물",
    labelEn: "building",
    prompts: ["a photo of a building", "architecture and buildings", "the exterior of a building"],
  },
  {
    id: "city",
    labelKo: "도시",
    labelEn: "city",
    prompts: ["a city street", "an urban city view", "buildings in a city"],
  },
  {
    id: "vehicle",
    labelKo: "차량",
    labelEn: "vehicle",
    prompts: ["a photo of a vehicle", "a car on the road", "a motor vehicle"],
  },
  {
    id: "indoor",
    labelKo: "실내",
    labelEn: "indoor",
    prompts: ["an indoor photo", "the inside of a room", "an interior space"],
  },
  {
    id: "night",
    labelKo: "야간",
    labelEn: "night",
    prompts: ["a photo taken at night", "a dark night scene", "nighttime lights"],
  },
  {
    id: "screenshot",
    labelKo: "스크린샷",
    labelEn: "screenshot",
    prompts: ["a computer screenshot", "a screenshot of a user interface", "a captured phone screen"],
  },
  {
    id: "other",
    labelKo: "기타",
    labelEn: "other",
    prompts: ["a random unrelated photo", "an object not covered by the categories", "miscellaneous content"],
    hidden: true,
  },
]);
export const KO_EN = Object.freeze({
  고양이: "cat",
  강아지: "dog",
  개: "dog",
  사람: "person",
  아기: "baby",
  셀카: "selfie",
  음식: "food",
  꽃: "flower",
  나무: "tree",
  자동차: "car",
  차량: "vehicle",
  자전거: "bicycle",
  바다: "ocean",
  산: "mountain",
  하늘: "sky",
  건물: "building",
  도시: "city",
  풍경: "landscape",
  새: "bird",
  물고기: "fish",
  문서: "document",
  영수증: "receipt",
  스크린샷: "screenshot",
  실내: "indoor room",
  야간: "night scene",
  야경: "night city view",
});

export const SEARCH_NEGATIVE_PROMPTS = Object.freeze([
  "a random unrelated photo",
  "background scenery",
  "an unrelated object",
]);
